library(ggplot2)
library(spatstat)
library(maptools)

# set frames_dir to a place where you will store 2K+ pngs
frames_dir = "/Users/mike/Data/frames/"

# the file 'afg.data' is generated by load_data.R
load("afg.data") # afg.data
afg = afg.data
afg$data$Type = factor(afg$data$Type)

# let's only look at one type of event
l = "Explosive Hazard"
afg$data = afg$data[afg$data$Type==l,]

# we need to set this as the polygon files we've got have some overlaps
spatstat.options(checkpolygons = FALSE) 

# build the window that creates the outline of Afghanistan
win = as(afg$outline, "owin")
# we need to "fortify" the polygons to plot them with ggplot
fortified.roads = fortify.SpatialLinesDataFrame(afg$ringroad)
fortified.outline = fortify.SpatialPolygons(afg$outline)
fortified.admin = fortify.SpatialPolygons(afg$admin)
# extract the settlement data
sett = data.frame(
    x=afg$sett$LON,
    y=afg$sett$LAT,
    name=as.character(afg$sett$NAME)
)
# extract time in a usable format
t = unclass(as.POSIXct.Date(afg$data$DateOccurred))
# build some useful time amounts
unix_start = as.Date("1970-01-01")
day_duration = 60 * 60 * 24 # seconds
now = t[1]                  # seconds since unix_start
num_days = round(t[length(t)]-now) / day_duration # how many actual days we have
one_month = day_duration * 31 # this is our time window

# upper and lower limits
cmax = 10
cmin = 0

# test 2009
now = now + (one_month * 12 * 5)

for (day in seq(10)){
    # figure out which points we want to smooth over for this day
    time.flags = (t > (now - one_month)) & (t < now)
    #today.flags = (t > now-(2*day_duration)) & (t < now+(2*day_duration))
    # increment time
    now = now+day_duration
    # extract the relevant points
    locns = data.frame(
        long = afg$data$Longitude[time.flags],
        lat = afg$data$Latitude[time.flags],
        label = afg$data$Type[time.flags]
    )
    #locns.today = data.frame(
    #    long = afg$data$Longitude[today.flags],
    #    lat = afg$data$Latitude[today.flags],
    #    label = afg$data$Type[today.flags]
    #)
    # build a ppp object for the density estimation
    afg.points = as.ppp(ppp(
        locns$long[!is.na(locns$long)], 
        locns$lat[!is.na(locns$lat)], 
        window = win
    ))
    # calculate kernel smoothing
    d = density(afg.points,0.2)
    img = t(as.matrix(d)) # note transposition
    # build grid points
    df = expand.grid(x=d$xcol, y=d$yrow)
    # pull out the image values
    df$z = melt(img)$value
    # threshold
    df$z[df$z > cmax] = cmax
    df$z[df$z < cmin] = cmin
    # build up plot
    p = ggplot(df,aes(x=x,y=y))
    # the tiling creates the heatmap
    p = p + geom_tile(aes(fill=z))
    # control the colour
    p = p + scale_fill_gradient(
        "Intensity",
        low="white",
        high="blue",
        limits=c(cmin, cmax),
        legend=FALSE # the legend is a bit hard to interpret
    )
    # add afghanistan boundary
    #p = p + geom_path(
    #    data=fortified.outline,  
    #    aes(y=lat,x=long,group=group), 
    #    size=1
    #)
    # add afghanistan administration boundaries
    #p = p + geom_path(
    #    data=fortified.admin,  
    #    aes(y=lat,x=long,group=group), 
    #    size=0.1
    #)
    # add roads
    p = p + geom_path(
        data=fortified.roads, 
        aes(y=lat,x=long,group=group), 
        size=1)
    p = p + geom_path(
        data=fortified.roads,    
        aes(y=lat,x=long,group=group), 
        size=0.5, 
        colour="white"
    )
    # add points, coloured by type
    #p = p + geom_point(
    #    data=locns.today, 
    #    aes(x=long,y=lat,colour=label)
    #)
    # add axis labels
    p = p + ylab("Latitude") + xlab("Longitude")
    # add title
    p = p + opts(title=paste("Intensity of",l,"Events"))
    # add the month and year
    now.posix = as.POSIXct(now,origin=unix_start)
    df.date = data.frame(x=70,y=30,t=format(now.posix,"%B %Y"))
    p = p + geom_text(data = df.date, aes(x=x, y=y, label=t), hjust=0)
    # add the place names
    for (i in seq(nrow(sett))){
        p = p + geom_text(
            data = sett[i,], 
            aes(x=x, y=y, label=name, size=4, legend=FALSE),
            hjust = sett[i,]$hjust,
            vjust = sett[i,]$vjust
        )
    }
    p = p + geom_point(data = sett, aes(x=x, y=y), legend=FALSE)
    # save the plot
    cat(paste("processing frame",day,"\n\t"))
    ggsave(
        filename=paste(frames_dir,'afghanistan_',day,'.png',sep=""), 
        plot=p,
        width = 14,
        height= 8,
        dpi=72
    )
}

# run this command to join the files (replacing the path as necessary)
# ffmpeg -f image2 -r 20 -i ~/Data/frames/afghanistan_%d.png -b 600k afghanistan.mp4